### ISSUE TITLE
Make the JavaScript client lib a node package

### ISSUE THREAD

**Issue by supermajor** [falk-werner/webfuse#7]
As a web developer I'd like to use the client app as a library in my own projects. 

Therefore, I propose to make the JavaScript client a node package and publish it on the official npm registry.

**Comment by falk-werner** [comment]
Nice idea. Once the API is stable, an npm package will be built.

**Comment by falk-werner** [comment]
@supermajor : I have a first propsal for JavaScript API at [example/daemon/www/js/wsfs](https://github.com/falk-werner/fuse-wsfs/tree/master/example/daemon/www/js/wsfs).
Would you perform a review, please?

**Comment by falk-werner** [comment]
Javascript example was moved to into a separate repository:
[https://github.com/falk-werner/webfuse-example](https://github.com/falk-werner/webfuse-example)
