### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by falk-werner** [falk-werner/webfuse#8]
@nosamad , @supermajor 
I would like to rename the project, since the current name is not pronouncable.
I'm in favor of  _webfs_ or something alike, but any suggestions are welcome.

**What's your opion?**

**Comment by supermajor** [comment]
+1 
seems legit, as I always get confused when trying to remember  the ordering of those four letters. It would be highly preferable to use a name that can acutally be spoken out. IMHO, _webfs_ seems a valid choice refering to the latter arguments. You could also consider to use name like _webfuse_ to avoid the use of any abbriviation at all.

**Comment by falk-werner** [comment]
_webfuse_ is nice, since it could be abbreviated _wf_ ;-)
...but maybe too narcissistic

**Comment by falk-werner** [comment]
okay, let's rename the project...

**Comment by falk-werner** [comment]
Done ;-)
